-- =============================================================================
-- Macheo Ecolodge & Camping — seed data (generated by scripts/generate-seed.mjs)
-- =============================================================================
-- Run AFTER the migrations. Everything here is upsert-safe.
--
-- ⚠ DEMO contact values (phone / WhatsApp / email) are placeholders so a
--   fresh database is browsable. Replace them in Admin → Contact information
--   with the confirmed numbers before the site is shared publicly.
--   Demo rooms, tents and experiences are seeded UNPUBLISHED where possible;
--   nothing invented reaches guests until an admin publishes it.
-- =============================================================================

-- site_settings
insert into public.site_settings (id, site_title, meta_description)
values (
  1,
  'Macheo Ecolodge & Camping | Stay, Camp & Explore Lake Kivu',
  'Macheo Ecolodge & Camping in Karongi (Kibuye), Rwanda — rooms, camping, a restaurant and bar, and lake experiences on the shores of Lake Kivu.'
)
on conflict (id) do update
  set site_title = excluded.site_title,
      meta_description = excluded.meta_description;

-- business_info (DEMO contact values — see header)
insert into public.business_info (
  id, name, tagline, street, city, country, phone, whatsapp, email,
  directions_url, opening_hours
)
values (
  1,
  'Macheo Ecolodge & Camping',
  'Stay closer to nature. Experience Lake Kivu.',
  null,
  'Karongi (Kibuye)',
  'Rwanda',
  '+250788000111',
  '+250788000111',
  'hello@macheo.example',
  null,
  '[]'::jsonb
)
on conflict (id) do update
  set name = excluded.name,
      tagline = excluded.tagline,
      city = excluded.city,
      country = excluded.country,
      phone = excluded.phone,
      whatsapp = excluded.whatsapp,
      email = excluded.email;

-- site_content (one row; NULL fields fall back to built-in defaults)
insert into public.site_content (id)
values (1)
on conflict (id) do nothing;

-- hero_media — the bundled photograph as the active hero image
insert into public.hero_media (title, subtitle, video_url, poster_url, is_active)
select
  'Macheo Ecolodge & Camping',
  'Stay closer to nature. Experience Lake Kivu.',
  null,
  '/images/macheo/hero-lake.jpg',
  true
where not exists (select 1 from public.hero_media where is_active);

-- accommodations — DEMO rows, created UNPUBLISHED (admin publishes after review)
insert into public.accommodations (
  kind, name, slug, tagline, description, images, capacity, beds, amenities,
  tent_info, price, available, featured, published, sort_order
)
values (
  'room', 'Lake View Room', 'lake-view-room', 'Wake up to the water.', 'A comfortable room with warm natural materials and a view towards Lake Kivu. (Demo entry — edit or replace before publishing.)',
  array['/images/macheo/room-lake.jpg'],
  2, '1 queen bed', array['Lake view', 'Wi-Fi', 'Hot shower', 'Towels'],
  null, null, true, false, false, 0
)
on conflict (slug) do nothing;

insert into public.accommodations (
  kind, name, slug, tagline, description, images, capacity, beds, amenities,
  tent_info, price, available, featured, published, sort_order
)
values (
  'room', 'Garden Family Room', 'garden-family-room', 'Space for the whole crew.', 'A larger room opening onto the gardens, for families and small groups. (Demo entry — edit or replace before publishing.)',
  array['/images/macheo/room-lake.jpg'],
  4, '2 double beds', array['Garden view', 'Wi-Fi', 'Hot shower'],
  null, null, true, false, false, 1
)
on conflict (slug) do nothing;

insert into public.accommodations (
  kind, name, slug, tagline, description, images, capacity, beds, amenities,
  tent_info, price, available, featured, published, sort_order
)
values (
  'camping', 'Lakeside Tent Pitch', 'lakeside-tent-pitch', 'Pitch up near the water.', 'Camping ground close to the lake with access to all lodge facilities. (Demo entry — describe the real setup before publishing.)',
  array['/images/macheo/camping-tents.jpg'],
  2, null, array['Lake access', 'Shared facilities', 'Campfire area'],
  'Bring your own tent, or ask us about tents on site.', null, true, false, false, 2
)
on conflict (slug) do nothing;

insert into public.accommodations (
  kind, name, slug, tagline, description, images, capacity, beds, amenities,
  tent_info, price, available, featured, published, sort_order
)
values (
  'camping', 'Furnished Safari Tent', 'furnished-safari-tent', 'Camping with a bed in it.', 'A ready-pitched tent with real beds and bedding — the outdoors without the packing. (Demo entry — confirm the actual setup before publishing.)',
  array['/images/macheo/camping-tents.jpg'],
  2, null, array['Beds & linen', 'Lantern', 'Shared facilities'],
  'Pre-pitched tent with beds and linen.', null, true, false, false, 3
)
on conflict (slug) do nothing;

-- experiences — DEMO rows with no invented prices or schedules
insert into public.experiences (title, description, image_url, price, duration, category, active, sort_order)
values ('Boat Experience on Lake Kivu', 'Time on the water with a local boat — the lake, the islands and the light. (Confirm details and pricing before promoting.)', '/images/macheo/boat-lake.jpg', null, null, 'Lake', true, 0)
on conflict do nothing;

insert into public.experiences (title, description, image_url, price, duration, category, active, sort_order)
values ('Cycling the Congo-Nile Trail', 'Ride one of the great lake trails — green hills, lake glimpses and village life. (Confirm route and logistics before promoting.)', '/images/macheo/cycling-trail.jpg', null, null, 'Adventure', true, 1)
on conflict do nothing;

insert into public.experiences (title, description, image_url, price, duration, category, active, sort_order)
values ('Nature & Garden Walk', 'A slow walk through the gardens and along the shore. (Confirm details before promoting.)', '/images/macheo/garden-path.jpg', null, null, 'Nature', true, 2)
on conflict do nothing;

insert into public.experiences (title, description, image_url, price, duration, category, active, sort_order)
values ('Water Activities', 'Swimming and water time on the lake, as conditions allow. (Confirm what is offered before promoting.)', '/images/macheo/lake-mountains.jpg', null, null, 'Lake', true, 3)
on conflict do nothing;

-- menu — demo structure from data/menu.ts (no prices)
insert into public.menu_categories (slug, name, intro, sort_order, published)
values ('food', 'Food', 'Fresh, lake-side cooking — breakfast, lunch and dinner.', 0, true)
on conflict (slug) do nothing;

insert into public.menu_sections (category_id, title, note, sort_order)
select c.id, null, null, 1
from public.menu_categories c
where c.slug = 'food'
  and not exists (
    select 1 from public.menu_sections s
    where s.category_id = c.id and s.title is not distinct from null
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Breakfast Plates', 'Fruit, eggs, toast and local honey — a slow start with lake views.', null,
       '{}', '[]'::jsonb,
       null, true, 0
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'food'
  and s.title is not distinct from null
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Breakfast Plates'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Fresh Lake Fish', 'The day''s catch from Lake Kivu, grilled and served with sides.', null,
       '{}', '[]'::jsonb,
       'Subject to the day''s catch', true, 1
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'food'
  and s.title is not distinct from null
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Fresh Lake Fish'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'From the Grill', 'Grilled meats and vegetables, cooked over open heat.', null,
       '{}', '[]'::jsonb,
       null, true, 2
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'food'
  and s.title is not distinct from null
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'From the Grill'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Garden & Vegetarian Plates', 'Seasonal vegetables, beans and grains from the hills.', null,
       '{}', '[]'::jsonb,
       null, true, 3
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'food'
  and s.title is not distinct from null
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Garden & Vegetarian Plates'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Snacks & Small Plates', 'Light bites for the terrace — perfect with a cold drink.', null,
       '{}', '[]'::jsonb,
       null, true, 4
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'food'
  and s.title is not distinct from null
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Snacks & Small Plates'
  );

insert into public.menu_categories (slug, name, intro, sort_order, published)
values ('drinks', 'Drinks', 'From morning coffee to sundowners at the bar.', 1, true)
on conflict (slug) do nothing;

insert into public.menu_sections (category_id, title, note, sort_order)
select c.id, 'Hot', null, 2
from public.menu_categories c
where c.slug = 'drinks'
  and not exists (
    select 1 from public.menu_sections s
    where s.category_id = c.id and s.title is not distinct from 'Hot'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Rwandan Coffee', 'Locally grown, freshly brewed.', null,
       '{}', '[]'::jsonb,
       null, true, 0
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'drinks'
  and s.title is not distinct from 'Hot'
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Rwandan Coffee'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Tea & Herbal Infusions', null, null,
       '{}', '[]'::jsonb,
       null, true, 1
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'drinks'
  and s.title is not distinct from 'Hot'
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Tea & Herbal Infusions'
  );

insert into public.menu_sections (category_id, title, note, sort_order)
select c.id, 'Cold', null, 3
from public.menu_categories c
where c.slug = 'drinks'
  and not exists (
    select 1 from public.menu_sections s
    where s.category_id = c.id and s.title is not distinct from 'Cold'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Fresh Juices', null, null,
       '{}', '[]'::jsonb,
       null, true, 0
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'drinks'
  and s.title is not distinct from 'Cold'
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Fresh Juices'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Soft Drinks & Water', null, null,
       '{}', '[]'::jsonb,
       null, true, 1
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'drinks'
  and s.title is not distinct from 'Cold'
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Soft Drinks & Water'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Beers', null, null,
       '{}', '[]'::jsonb,
       null, true, 2
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'drinks'
  and s.title is not distinct from 'Cold'
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Beers'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Wines & Spirits', null, null,
       '{}', '[]'::jsonb,
       'Ask the bar for the current selection', true, 3
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'drinks'
  and s.title is not distinct from 'Cold'
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Wines & Spirits'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Cocktails & Mocktails', null, null,
       '{}', '[]'::jsonb,
       null, true, 4
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'drinks'
  and s.title is not distinct from 'Cold'
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Cocktails & Mocktails'
  );

insert into public.menu_categories (slug, name, intro, sort_order, published)
values ('specials', 'Specials', 'Ask about today''s special — it changes with the season and the catch.', 2, true)
on conflict (slug) do nothing;

insert into public.menu_sections (category_id, title, note, sort_order)
select c.id, null, null, 4
from public.menu_categories c
where c.slug = 'specials'
  and not exists (
    select 1 from public.menu_sections s
    where s.category_id = c.id and s.title is not distinct from null
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Chef''s Special of the Day', 'Ask your server what today brings.', null,
       '{}', '[]'::jsonb,
       null, true, 0
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'specials'
  and s.title is not distinct from null
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Chef''s Special of the Day'
  );

insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, 'Sundowners on the Terrace', 'The best seat for the light over the lake.', null,
       '{}', '[]'::jsonb,
       null, true, 1
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = 'specials'
  and s.title is not distinct from null
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = 'Sundowners on the Terrace'
  );

-- gallery_items — the bundled photography
insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/hero-lake.jpg', 'Lake Kivu at golden hour', 'Lake Kivu at golden hour seen from the hills', true, 'Lake Kivu', true, 0
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/hero-lake.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/lake-mountains.jpg', 'The lake and the mountains', 'Lake Kivu and the surrounding mountains', true, 'Lake Kivu', true, 1
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/lake-mountains.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/room-lake.jpg', 'A room at the lodge', 'A comfortable ecolodge room', true, 'Stay', true, 2
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/room-lake.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/camping-tents.jpg', 'Camping at Macheo', 'Tents near the lake at dusk', true, 'Camping', true, 3
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/camping-tents.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/restaurant-terrace.jpg', 'Dinner on the terrace', 'The restaurant terrace set for dinner', true, 'Restaurant & Bar', true, 4
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/restaurant-terrace.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/bar-drinks.jpg', 'At the bar', 'Drinks at the bar', false, 'Restaurant & Bar', true, 5
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/bar-drinks.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/food-plate.jpg', 'From the kitchen', 'A freshly prepared plate', true, 'Restaurant & Bar', true, 6
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/food-plate.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/boat-lake.jpg', 'On the water', 'A boat crossing Lake Kivu', true, 'Experiences', true, 7
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/boat-lake.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/cycling-trail.jpg', 'Riding the trail', 'Cyclists on the Congo-Nile Trail', false, 'Experiences', true, 8
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/cycling-trail.jpg');

insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select '/images/macheo/garden-path.jpg', 'The gardens', 'The garden path at Macheo', false, 'Nature', true, 9
where not exists (select 1 from public.gallery_items where image_url = '/images/macheo/garden-path.jpg');

-- Done. Sign in with an admin account to review and publish the demo rows.
