/**
 * Detects the official logo and writes `data/logo.generated.ts`.
 *
 * Runs automatically before `dev` and `build` (see the `predev` / `prebuild`
 * scripts in package.json), so installing the real logo is a pure drop-in:
 *
 *     cp your-logo.png public/images/logo.png
 *     npm run build
 *
 * No code change, no config edit. If no logo file is present, the generated
 * module exports `null` and every brand lock-up falls back to the typographic
 * wordmark — the logo is never recreated or approximated.
 *
 * It also records whether the file has an alpha channel. A logo saved as an
 * opaque rectangle would otherwise show white corners against the dark hero,
 * so opaque circular badges get a circular mask (which removes background,
 * not artwork).
 */

import { existsSync } from "node:fs";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * The project root, resolved from THIS FILE's location (`scripts/..`) rather
 * than `process.cwd()`.
 *
 * The build platform chooses the working directory, not us: locally it is the
 * repo, on Vercel it is /vercel/path0, and a monorepo install may run the
 * script from somewhere else entirely. Anchoring to the script itself means
 * `public/images` and `data/logo.generated.ts` are found wherever it runs,
 * with no platform-specific path anywhere.
 */
const PROJECT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

const IMAGES_DIR = path.join(PROJECT_ROOT, "public", "images");
const OUT_FILE = path.join(PROJECT_ROOT, "data", "logo.generated.ts");

/** Preference order: vector first, then lossless, then lossy. */
const CANDIDATES = ["logo.svg", "logo.png", "logo.webp", "logo.jpg", "logo.jpeg"];

const HEADER = `// AUTO-GENERATED by scripts/detect-logo.mjs — do not edit by hand.
// Regenerated on every \`npm run dev\` and \`npm run build\`.

export type DetectedLogo = {
  src: string;
  width: number;
  height: number;
  /** "circle" when the source is opaque, so background corners are hidden. */
  mask: "circle" | "none";
};

`;

async function main() {
  /* `fs.writeFile` does not create parent directories, so writing straight
     into data/ fails with ENOENT whenever that folder is absent — a fresh
     build container is exactly that case, and this is what broke the Vercel
     prebuild. `recursive: true` is a no-op when the directory already
     exists, so this is safe to run on every build.

     The generated module is also committed to Git: data/site.ts imports it,
     so `npm run typecheck` on a fresh clone works before any build has run.
     This script regenerates it either way — the build never depends on the
     committed copy being present. */
  await mkdir(path.dirname(OUT_FILE), { recursive: true });

  const found = CANDIDATES.find((name) => existsSync(path.join(IMAGES_DIR, name)));

  if (!found) {
    await writeFile(
      OUT_FILE,
      `${HEADER}export const detectedLogo: DetectedLogo | null = null;\n`,
    );
    console.log("No logo found in public/images/ — using the typographic wordmark.");
    console.log("Drop in public/images/logo.png (or .svg/.webp) and re-run to use it.");
    return;
  }

  const file = path.join(IMAGES_DIR, found);
  // Imported lazily: with no logo file there is nothing to measure, and the
  // script must not fail (or need sharp's native binary at all) on the path
  // that every build without a logo takes.
  const { default: sharp } = await import("sharp");
  const meta = await sharp(file).metadata();

  const width = meta.width ?? 512;
  const height = meta.height ?? 512;

  // SVGs are treated as transparent; raster files are inspected.
  const isVector = found.endsWith(".svg");
  const hasAlpha = isVector ? true : Boolean(meta.hasAlpha);

  // Only mask when the artwork is roughly square — a circular crop on a wide
  // wordmark would cut it off, which we must never do.
  const ratio = width / height;
  const nearlySquare = ratio > 0.85 && ratio < 1.18;
  const mask = !hasAlpha && nearlySquare ? "circle" : "none";

  const body = `export const detectedLogo: DetectedLogo | null = {
  src: "/images/${found}",
  width: ${width},
  height: ${height},
  mask: "${mask}",
};
`;

  await writeFile(OUT_FILE, HEADER + body);

  console.log(`Logo: public/images/${found} (${width}×${height}, mask: ${mask})`);
  if (mask === "circle") {
    console.log(
      "  Note: the file is opaque, so a circular mask hides its background corners.",
    );
  }
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
