/**
 * Generates supabase/seed.sql from the committed data files plus the demo
 * hospitality content below.
 *
 *   npm run seed:generate
 *
 * WHAT IS SEEDED
 *   - business_info   — Macheo's confirmed basics PLUS clearly-marked DEMO
 *                       contact values (phone/WhatsApp/email) so a fresh
 *                       database is browsable. Replace them from the
 *                       dashboard (Contact information) before going live.
 *   - hero_media      — the bundled Lake Kivu photograph as the active hero.
 *   - accommodations  — neutral demo rooms + camping options (unpublished,
 *                       so nothing invented ever appears on the public site
 *                       until an admin reviews and publishes each one).
 *   - experiences     — neutral demo experiences (also unpublished-in-spirit:
 *                       active, but holding no invented prices or schedules).
 *   - menu            — the neutral demo menu from data/menu.ts (no prices).
 *   - gallery_items   — the bundled photography, categorised, some featured.
 *   - site_content    — one empty row (defaults live in code).
 *
 * No seed row invents a price, a schedule or a historical fact.
 */

import { writeFile } from "node:fs/promises";
import path from "node:path";

const OUT = path.join(process.cwd(), "supabase", "seed.sql");

/** SQL string literal, or NULL. */
function q(value) {
  if (value === null || value === undefined || value === "") return "null";
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** SQL jsonb literal. */
function j(value) {
  return `'${JSON.stringify(value).replace(/'/g, "''")}'::jsonb`;
}

/** text[] literal. */
function arr(values) {
  if (!values || values.length === 0) return "'{}'";
  return `array[${values.map((v) => q(v)).join(", ")}]`;
}

/** "6,000 RWF" -> 6000; null stays null. */
function priceToInt(value) {
  if (value === null || value === undefined) return null;
  const digits = String(value).replace(/[^\d]/g, "");
  if (digits === "") return null;
  return Number.parseInt(digits, 10);
}

/** Demo contact values — replace with confirmed ones before launch. */
const DEMO_CONTACT = {
  phone: "+250788000111",
  whatsapp: "+250788000111",
  email: "hello@macheo.example",
};

async function main() {
  const { menu } = await import("../data/menu.ts");
  const { lodge } = await import("../data/macheo.ts");

  const lines = [];
  const push = (s = "") => lines.push(s);

  push("-- =============================================================================");
  push("-- Macheo Ecolodge & Camping — seed data (generated by scripts/generate-seed.mjs)");
  push("-- =============================================================================");
  push("-- Run AFTER the migrations. Everything here is upsert-safe.");
  push("--");
  push("-- ⚠ DEMO contact values (phone / WhatsApp / email) are placeholders so a");
  push("--   fresh database is browsable. Replace them in Admin → Contact information");
  push("--   with the confirmed numbers before the site is shared publicly.");
  push("--   Demo rooms, tents and experiences are seeded UNPUBLISHED where possible;");
  push("--   nothing invented reaches guests until an admin publishes it.");
  push("-- =============================================================================");
  push();

  /* ---------------------------------------------------------------- settings */
  push("-- site_settings");
  push(`insert into public.site_settings (id, site_title, meta_description)
values (
  1,
  'Macheo Ecolodge & Camping | Stay, Camp & Explore Lake Kivu',
  'Macheo Ecolodge & Camping in Karongi (Kibuye), Rwanda — rooms, camping, a restaurant and bar, and lake experiences on the shores of Lake Kivu.'
)
on conflict (id) do update
  set site_title = excluded.site_title,
      meta_description = excluded.meta_description;`);
  push();

  /* ----------------------------------------------------------- business info */
  push("-- business_info (DEMO contact values — see header)");
  push(`insert into public.business_info (
  id, name, tagline, street, city, country, phone, whatsapp, email,
  directions_url, opening_hours
)
values (
  1,
  ${q(lodge.name)},
  ${q(lodge.tagline)},
  ${q(null)},
  ${q(lodge.city)},
  ${q(lodge.country)},
  ${q(DEMO_CONTACT.phone)},
  ${q(DEMO_CONTACT.whatsapp)},
  ${q(DEMO_CONTACT.email)},
  ${q(null)},
  ${j([])}
)
on conflict (id) do update
  set name = excluded.name,
      tagline = excluded.tagline,
      city = excluded.city,
      country = excluded.country,
      phone = excluded.phone,
      whatsapp = excluded.whatsapp,
      email = excluded.email;`);
  push();

  /* ------------------------------------------------------------ site_content */
  push("-- site_content (one row; NULL fields fall back to built-in defaults)");
  push(`insert into public.site_content (id)
values (1)
on conflict (id) do nothing;`);
  push();

  /* -------------------------------------------------------------- hero media */
  push("-- hero_media — the bundled photograph as the active hero image");
  push(`insert into public.hero_media (title, subtitle, video_url, poster_url, is_active)
select
  'Macheo Ecolodge & Camping',
  'Stay closer to nature. Experience Lake Kivu.',
  null,
  '/images/macheo/hero-lake.jpg',
  true
where not exists (select 1 from public.hero_media where is_active);`);
  push();

  /* ---------------------------------------------------------- accommodations */
  push("-- accommodations — DEMO rows, created UNPUBLISHED (admin publishes after review)");
  const accommodations = [
    {
      kind: "room",
      name: "Lake View Room",
      slug: "lake-view-room",
      tagline: "Wake up to the water.",
      description:
        "A comfortable room with warm natural materials and a view towards Lake Kivu. (Demo entry — edit or replace before publishing.)",
      capacity: 2,
      beds: "1 queen bed",
      amenities: ["Lake view", "Wi-Fi", "Hot shower", "Towels"],
      price: null,
    },
    {
      kind: "room",
      name: "Garden Family Room",
      slug: "garden-family-room",
      tagline: "Space for the whole crew.",
      description:
        "A larger room opening onto the gardens, for families and small groups. (Demo entry — edit or replace before publishing.)",
      capacity: 4,
      beds: "2 double beds",
      amenities: ["Garden view", "Wi-Fi", "Hot shower"],
      price: null,
    },
    {
      kind: "camping",
      name: "Lakeside Tent Pitch",
      slug: "lakeside-tent-pitch",
      tagline: "Pitch up near the water.",
      description:
        "Camping ground close to the lake with access to all lodge facilities. (Demo entry — describe the real setup before publishing.)",
      capacity: 2,
      tent_info: "Bring your own tent, or ask us about tents on site.",
      amenities: ["Lake access", "Shared facilities", "Campfire area"],
      price: null,
    },
    {
      kind: "camping",
      name: "Furnished Safari Tent",
      slug: "furnished-safari-tent",
      tagline: "Camping with a bed in it.",
      description:
        "A ready-pitched tent with real beds and bedding — the outdoors without the packing. (Demo entry — confirm the actual setup before publishing.)",
      capacity: 2,
      tent_info: "Pre-pitched tent with beds and linen.",
      amenities: ["Beds & linen", "Lantern", "Shared facilities"],
      price: null,
    },
  ];

  for (const a of accommodations) {
    push(`insert into public.accommodations (
  kind, name, slug, tagline, description, images, capacity, beds, amenities,
  tent_info, price, available, featured, published, sort_order
)
values (
  ${q(a.kind)}, ${q(a.name)}, ${q(a.slug)}, ${q(a.tagline)}, ${q(a.description)},
  ${arr(a.kind === "camping" ? ["/images/macheo/camping-tents.jpg"] : ["/images/macheo/room-lake.jpg"])},
  ${a.capacity ?? "null"}, ${q(a.beds ?? null)}, ${arr(a.amenities)},
  ${q(a.tent_info ?? null)}, ${a.price ?? "null"}, true, false, false, ${accommodations.indexOf(a)}
)
on conflict (slug) do nothing;`);
    push();
  }

  /* ------------------------------------------------------------- experiences */
  push("-- experiences — DEMO rows with no invented prices or schedules");
  const experiences = [
    {
      title: "Boat Experience on Lake Kivu",
      description:
        "Time on the water with a local boat — the lake, the islands and the light. (Confirm details and pricing before promoting.)",
      category: "Lake",
      image: "/images/macheo/boat-lake.jpg",
    },
    {
      title: "Cycling the Congo-Nile Trail",
      description:
        "Ride one of the great lake trails — green hills, lake glimpses and village life. (Confirm route and logistics before promoting.)",
      category: "Adventure",
      image: "/images/macheo/cycling-trail.jpg",
    },
    {
      title: "Nature & Garden Walk",
      description:
        "A slow walk through the gardens and along the shore. (Confirm details before promoting.)",
      category: "Nature",
      image: "/images/macheo/garden-path.jpg",
    },
    {
      title: "Water Activities",
      description:
        "Swimming and water time on the lake, as conditions allow. (Confirm what is offered before promoting.)",
      category: "Lake",
      image: "/images/macheo/lake-mountains.jpg",
    },
  ];

  experiences.forEach((x, index) => {
    push(`insert into public.experiences (title, description, image_url, price, duration, category, active, sort_order)
values (${q(x.title)}, ${q(x.description)}, ${q(x.image)}, null, null, ${q(x.category)}, true, ${index})
on conflict do nothing;`);
    push();
  });

  /* -------------------------------------------------------------------- menu */
  push("-- menu — demo structure from data/menu.ts (no prices)");
  let sectionOrder = 0;
  for (const category of menu) {
    push(`insert into public.menu_categories (slug, name, intro, sort_order, published)
values (${q(category.id)}, ${q(category.category)}, ${q(category.intro ?? null)}, ${menu.indexOf(category)}, true)
on conflict (slug) do nothing;`);
    push();

    for (const section of category.sections) {
      sectionOrder += 1;
      push(`insert into public.menu_sections (category_id, title, note, sort_order)
select c.id, ${q(section.title ?? null)}, ${q(section.note ?? null)}, ${sectionOrder}
from public.menu_categories c
where c.slug = ${q(category.id)}
  and not exists (
    select 1 from public.menu_sections s
    where s.category_id = c.id and s.title is not distinct from ${q(section.title ?? null)}
  );`);
      push();

      for (const item of section.items) {
        push(`insert into public.menu_items (section_id, name, description, price, dietary, variants, availability_note, available, sort_order)
select s.id, ${q(item.name)}, ${q(item.description ?? null)}, ${priceToInt(item.price) ?? "null"},
       ${arr(item.dietary ?? [])}, ${j((item.variants ?? []).map((v) => ({ label: v.label, price: priceToInt(v.price) })))},
       ${q(item.availability ?? null)}, true, ${section.items.indexOf(item)}
from public.menu_sections s
join public.menu_categories c on c.id = s.category_id
where c.slug = ${q(category.id)}
  and s.title is not distinct from ${q(section.title ?? null)}
  and not exists (
    select 1 from public.menu_items i where i.section_id = s.id and i.name = ${q(item.name)}
  );`);
        push();
      }
    }
  }

  /* ----------------------------------------------------------------- gallery */
  push("-- gallery_items — the bundled photography");
  const galleryItems = [
    { url: "/images/macheo/hero-lake.jpg", caption: "Lake Kivu at golden hour", category: "Lake Kivu", featured: true, alt: "Lake Kivu at golden hour seen from the hills" },
    { url: "/images/macheo/lake-mountains.jpg", caption: "The lake and the mountains", category: "Lake Kivu", featured: true, alt: "Lake Kivu and the surrounding mountains" },
    { url: "/images/macheo/room-lake.jpg", caption: "A room at the lodge", category: "Stay", featured: true, alt: "A comfortable ecolodge room" },
    { url: "/images/macheo/camping-tents.jpg", caption: "Camping at Macheo", category: "Camping", featured: true, alt: "Tents near the lake at dusk" },
    { url: "/images/macheo/restaurant-terrace.jpg", caption: "Dinner on the terrace", category: "Restaurant & Bar", featured: true, alt: "The restaurant terrace set for dinner" },
    { url: "/images/macheo/bar-drinks.jpg", caption: "At the bar", category: "Restaurant & Bar", featured: false, alt: "Drinks at the bar" },
    { url: "/images/macheo/food-plate.jpg", caption: "From the kitchen", category: "Restaurant & Bar", featured: true, alt: "A freshly prepared plate" },
    { url: "/images/macheo/boat-lake.jpg", caption: "On the water", category: "Experiences", featured: true, alt: "A boat crossing Lake Kivu" },
    { url: "/images/macheo/cycling-trail.jpg", caption: "Riding the trail", category: "Experiences", featured: false, alt: "Cyclists on the Congo-Nile Trail" },
    { url: "/images/macheo/garden-path.jpg", caption: "The gardens", category: "Nature", featured: false, alt: "The garden path at Macheo" },
  ];

  galleryItems.forEach((g, index) => {
    push(`insert into public.gallery_items (image_url, caption, alt_text, featured, category, published, sort_order)
select ${q(g.url)}, ${q(g.caption)}, ${q(g.alt)}, ${g.featured}, ${q(g.category)}, true, ${index}
where not exists (select 1 from public.gallery_items where image_url = ${q(g.url)});`);
    push();
  });

  push("-- Done. Sign in with an admin account to review and publish the demo rows.");

  await writeFile(OUT, lines.join("\n") + "\n");
  console.log(`Wrote ${OUT} (${lines.length} lines).`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
